import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from '@/components/SessionProvider'
import { getServerSession } from "next-auth/next"
// import {authOptions} from "/Users/bhubeshsr/Desktop/Bhubesh/reddit-clone/app/pages/api/auth/[...nextauth].ts"
import Header from "@/components/Header";
import {NextAuthProvider} from "/Users/bhubeshsr/Desktop/Bhubesh/reddit-clone/app/provider.js"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app', 
}
 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header></Header>
        <div className={inter.className}>{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
